### ISSUE TITLE
Missing factor in the PerturbedMultiplicative perturbation

### ISSUE THREAD

**Issue by BatyLeo** [axelparmentier/InferOpt.jl#81]
According to the paper, `θ_perturbed = θ .* exp.(ε .* Z .- ε^2)` ([here](https://github.com/axelparmentier/InferOpt.jl/blob/b9f4f69f1214338c54399fe4e00fa45e10b65e75/src/perturbed/multiplicative.jl#L55)) should be `θ_perturbed = θ .* exp.(ε .* Z .- ε^2 / 2)` instead

**Comment by gdalle** [comment]
Duplicate of #82
